### ISSUE TITLE
Start of the Extension: Making an SSH Connection

### ISSUE THREAD

**Issue by JMAR059** [JMAR059/open-horizon-docker-extension#1]
As discussed today, the base of the extension will work off a connection between a docker container and a pre-existing Open Horizon Management Hub terminal. So far, we have decided to work with the default container that the template extension for Docker Desktop uses, which is an Arch image. To test with our most familiar and already installed instance of Open Horizon Management Hub, we will try to SSH connect to an Ubuntu instance of it. Thus our goals for the following 2 weeks:

- Ensure that the Arch image is running on Docker using our Docker Desktop Extension
- Get familiar with Arch image and how to work with it in our backend
- Research possible ways to SSH connect from Arch image to separate Ubuntu image, in terms of opening ports and whatnot
- Make connection from Arch image to Ubuntu image, and test more basic features, like checking Ubuntu image specs and status

We will work primarily with the backend for now. Leave some features from the front-end like being able to specify the specific Ubuntu image for later, as well as other information we might want to get from the Ubuntu instance to the Docker Desktop Extension.

**Comment by Demopans** [comment]
> Make connection from Arch image to Ubuntu image, and test more basic features, like checking Ubuntu image specs and status
We really only need a way to ssh to the ubuntu image OH runs on.

**Comment by joewxboy** [comment]
So is your goal to SSH to the remote host so that you can run `hzn` CLI commands and parse the responses?

**Comment by Demopans** [comment]
> So is your goal to SSH to the remote host so that you can run `hzn` CLI commands and parse the responses?

For the time being, yes for the management hub. As for the future, I intend to include UI elements that translate into hzn commands.

**Comment by joewxboy** [comment]
It sounds like a great start and the right direction.  It's a lot less problematic than using the APIs directly.

**Comment by JMAR059** [comment]
Direction of how we connect and use HZN commands changed. Will be closing this issue for now. See #2
